region: ap-northeast-1
cluster: polaris-prod-shared
service: discordMusicLinkConverter-prod
service_definition: ecs-service-def.jsonnet
task_definition: ecs-task-def.jsonnet
timeout: 10m0s
plugins:
- name: tfstate
  config:
    url: s3://irofessional-main-tfstate/mrmr-discordmusiclinkconverterbot/terraform.tfstate