name: Deploy

on:
  pull_request:
    branches:
      - master
    types: 
      - closed

permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push image
        id: build-image
        run: |
          docker build -t $ECR_URL:$IMAGE_TAG .
          docker push $ECR_URL:$IMAGE_TAG
          echo "::set-output name=image::$ECR_URL:$IMAGE_TAG"
        env:
          ECR_URL: ${{ secrets.ECR_URI }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: terraform
        shell: bash
        run: terraform plan -input=false
        env:
          TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          TF_VAR_discord_bot_category: ${{ secrets.DISCORD_BOT_CATEGORY }}

      - name: Terraform Apply
        working-directory: terraform
        shell: bash
        run: terraform apply -input=false -auto-approve
        env:
          TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          TF_VAR_discord_bot_category: ${{ secrets.DISCORD_BOT_CATEGORY }}
      
      - name: Terraform Outputs
        id: output
        working-directory: terraform
        shell: bash
        run: terraform output -raw ecs_service_name
      
      - name: Render task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
           task-definition: terraform/ecs-task-definition.json
           container-name: discordMusicLinkConverter
           image: ${{ steps.build-image.outputs.image }}
      
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ steps.output.outputs.stdout }}
          cluster: ${{ secrets.ECS_CLUSTER }}
      