name: Terraform plan

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches: 
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    env:
      TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
      TF_VAR_discord_bot_category: ${{ secrets.DISCORD_BOT_CATEGORY }}
      TF_VAR_ecs_cluster: ${{ secrets.ECS_CLUSTER }}
      TF_VAR_ecr_uri: ${{ secrets.ECR_URI }}
      TF_VAR_image_tag: ${{ github.sha }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: terraform
        shell: bash
        run: terraform plan -input=false